-- Import food items from CSV
-- This script inserts all 145 items from groente-fruit.csv

INSERT INTO public.food_items (name_nl, type, nutrient) VALUES
('Aardbei', 'fruit', 'vitamine C'),
('Abrikoos', 'fruit', 'vitamine A'),
('Ananas', 'fruit', 'antioxidanten'),
('Appel', 'fruit', 'vezels'),
('Appelbanaan', 'fruit', 'kalium'),
('Avocado', 'fruit', 'kalium'),
('Banaan', 'fruit', 'kalium'),
('Bergamot', 'fruit', 'antioxidanten'),
('Blauwe bes', 'fruit', 'antioxidanten'),
('Braam', 'fruit', 'antioxidanten'),
('Broodvrucht', 'fruit', 'antioxidanten'),
('Calamondin', 'fruit', 'antioxidanten'),
('Cantaloupe', 'fruit', 'antioxidanten'),
('Cassabanana', 'fruit', 'antioxidanten'),
('Cherimoya', 'fruit', 'antioxidanten'),
('Chinapeer', 'fruit', 'vezels'),
('Citroen', 'fruit', 'vitamine C'),
('Clementine', 'fruit', 'vitamine C'),
('Costa Rica-guave', 'fruit', 'antioxidanten'),
('Curuba', 'fruit', 'antioxidanten'),
('Custardappel', 'fruit', 'antioxidanten'),
('Dadel', 'fruit', 'antioxidanten'),
('Doerian', 'fruit', 'antioxidanten'),
('Druif', 'fruit', 'antioxidanten'),
('Feijoa', 'fruit', 'antioxidanten'),
('Gele mombinpruim', 'fruit', 'vitamine A'),
('Genipapo', 'fruit', 'antioxidanten'),
('Goudbes', 'fruit', 'antioxidanten'),
('Granaatappel', 'fruit', 'vitamine C'),
('Grapefruit', 'fruit', 'vitamine C'),
('Grosella', 'fruit', 'antioxidanten'),
('Grote bosaardbei', 'fruit', 'antioxidanten'),
('Guave', 'fruit', 'antioxidanten'),
('Honingmeloen', 'fruit', 'vitamine C'),
('Ikakopruim', 'fruit', 'antioxidanten'),
('Jabuticaba', 'fruit', 'antioxidanten'),
('Jackfruit', 'fruit', 'antioxidanten'),
('Jakhalsbes', 'fruit', 'antioxidanten'),
('Jambolan', 'fruit', 'antioxidanten'),
('Japanse wijnbes', 'fruit', 'antioxidanten'),
('Jujube', 'fruit', 'antioxidanten'),
('Kaki', 'fruit', 'vitamine A'),
('Kapoelasan', 'fruit', 'antioxidanten'),
('Kei-appel', 'fruit', 'antioxidanten'),
('Kers', 'fruit', 'antioxidanten'),
('Ketembilla', 'fruit', 'antioxidanten'),
('Kiwi', 'fruit', 'vitamine C'),
('Knippa', 'fruit', 'antioxidanten'),
('Kokosnoot', 'fruit', 'water'),
('Korlan', 'fruit', 'antioxidanten'),
('Kruipbraam', 'fruit', 'antioxidanten'),
('Kruisbes', 'fruit', 'antioxidanten'),
('Kumquat', 'fruit', 'antioxidanten'),
('Kweepeer', 'fruit', 'vezels'),
('Langsat', 'fruit', 'antioxidanten'),
('Lijsterbes', 'fruit', 'antioxidanten'),
('Limoen', 'fruit', 'vitamine C'),
('Longan', 'fruit', 'antioxidanten'),
('Loquat', 'fruit', 'antioxidanten'),
('Lotusvrucht', 'fruit', 'antioxidanten'),
('Lucuma', 'fruit', 'antioxidanten'),
('Lulo', 'fruit', 'antioxidanten'),
('Lychee', 'fruit', 'antioxidanten'),
('Mabolo', 'fruit', 'antioxidanten'),
('Mamey sapota', 'fruit', 'antioxidanten'),
('Mandarijn', 'fruit', 'vitamine C'),
('Mangistan', 'fruit', 'antioxidanten'),
('Mango', 'fruit', 'vitamine A'),
('Marang', 'fruit', 'antioxidanten'),
('Meloen', 'fruit', 'antioxidanten'),
('Mini-kiwi', 'fruit', 'antioxidanten'),
('Mispel', 'fruit', 'vezels'),
('Moendoe', 'fruit', 'antioxidanten'),
('Moerbei', 'fruit', 'antioxidanten'),
('Moriche', 'fruit', 'antioxidanten'),
('Nance', 'fruit', 'antioxidanten'),
('Nashipeer', 'fruit', 'vezels'),
('Natalpruim', 'fruit', 'antioxidanten'),
('Nectarine', 'fruit', 'vitamine A'),
('Noni', 'fruit', 'antioxidanten'),
('Olifantsappel', 'fruit', 'antioxidanten'),
('Olijf', 'fruit', 'antioxidanten'),
('Orinoco-appel', 'fruit', 'antioxidanten'),
('Papaja', 'fruit', 'vitamine C'),
('Papeda', 'fruit', 'antioxidanten'),
('Passievrucht', 'fruit', 'vitamine C'),
('Pawpaw', 'fruit', 'antioxidanten'),
('Peer', 'fruit', 'vezels'),
('Pepino', 'fruit', 'antioxidanten'),
('Perzik', 'fruit', 'vitamine A'),
('Perzikpalm', 'fruit', 'antioxidanten'),
('Pitaja', 'fruit', 'vitamine A'),
('Pitomba I', 'fruit', 'antioxidanten'),
('Pitomba II', 'fruit', 'antioxidanten'),
('Pluot', 'fruit', 'vitamine A'),
('Pomelo', 'fruit', 'antioxidanten'),
('Pompelmoes', 'fruit', 'vitamine C'),
('Prachtframboos', 'fruit', 'antioxidanten'),
('Prachtige mango', 'fruit', 'antioxidanten'),
('Pruim', 'fruit', 'vitamine A'),
('Ramboetan', 'fruit', 'antioxidanten'),
('Rijsbes', 'fruit', 'antioxidanten'),
('Rode bes', 'fruit', 'antioxidanten'),
('Rode bosbes', 'fruit', 'antioxidanten'),
('Rode moerbei', 'fruit', 'antioxidanten'),
('Rode mombinpruim', 'fruit', 'vitamine A'),
('Rozenbottel', 'fruit', 'antioxidanten'),
('Salak', 'fruit', 'antioxidanten'),
('Santol', 'fruit', 'antioxidanten'),
('Sapodilla', 'fruit', 'antioxidanten'),
('Satsuma', 'fruit', 'antioxidanten'),
('Schroefpalm', 'fruit', 'vitamine C'),
('Sharonfruit', 'fruit', 'vitamine C'),
('Sinaasappel', 'fruit', 'vitamine C'),
('Slijmappel', 'fruit', 'antioxidanten'),
('Soncoya', 'fruit', 'antioxidanten'),
('Stervrucht', 'fruit', 'vitamine C'),
('Stinkende mango', 'fruit', 'antioxidanten'),
('Stranddruif', 'fruit', 'antioxidanten'),
('Surinaamse kers', 'fruit', 'antioxidanten'),
('Sweetie', 'fruit', 'antioxidanten'),
('Switbonki', 'fruit', 'antioxidanten'),
('Tamarillo', 'fruit', 'vitamine C'),
('Tjampedak', 'fruit', 'antioxidanten'),
('Tomaat', 'groente', 'vitamine C'),
('Topinamboer', 'groente', 'vezels'),
('Tuinkers', 'groente', 'foliumzuur'),
('Tuinboon', 'groente', 'foliumzuur'),
('Tuinmelde', 'groente', 'antioxidanten'),
('Ugli', 'fruit', 'antioxidanten'),
('Ui', 'groente', 'antioxidanten'),
('Veldsla', 'groente', 'water'),
('Veldzuring', 'groente', 'vezels'),
('Venkel', 'groente', 'antioxidanten'),
('Vijgenbladpompoen', 'groente', 'vitamine A'),
('Vleugelboon', 'groente', 'antioxidanten'),
('Witlof', 'groente', 'antioxidanten'),
('Wittekool', 'groente', 'antioxidanten'),
('Wortel', 'groente', 'vitamine A'),
('Wortelpeterselie', 'groente', 'vitamine A'),
('Yacón', 'groente', 'antioxidanten'),
('Zeekool', 'groente', 'antioxidanten'),
('Zonnewortel', 'groente', 'vitamine A'),
('Zuring', 'groente', 'vezels')
ON CONFLICT (name_nl) DO NOTHING;
